import { MetadataRoute } from 'next';

// Icons are generated by scripts/generate-brand-assets.mjs into app/.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Luxor Film - Documentary Production',
    short_name: 'Luxor Film',
    description: 'Documentary production company offering research, script development, interview production, drama, and full episode delivery.',
    start_url: '/',
    display: 'standalone',
    background_color: '#0A0A0A',
    theme_color: '#D4AF37',
    orientation: 'portrait-primary',
    scope: '/',
    categories: ['entertainment', 'video', 'business'],
    icons: [
      { src: '/icon.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/apple-icon.png', sizes: '180x180', type: 'image/png', purpose: 'any' },
    ],
    shortcuts: [
      {
        name: 'Our Work',
        short_name: 'Portfolio',
        description: 'View our portfolio',
        url: '/work',
      },
      {
        name: 'About',
        short_name: 'About',
        description: 'Learn about Luxor Film',
        url: '/about',
      },
    ],
  };
}
